[project]
name = "bnalphachecker"
version = "0.1.0"
description = "Binance account balance checker and USDT calculator"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.28.0",
    "schedule>=1.2.0",
    "loguru>=0.7.0"
]
